### ISSUE TITLE
Specs: Ability to Clone Assignments

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#227] opened 2016-07-04 11:03 UTC
Feature required:
- After an Assignment is created, Teachers need the ability to quickly clone/copy existing Assignments into a new one.

Extension of #226 
Requested by @aliburchard
cc @simoneduca @marten

**Comment by simoneduca** [comment] 2016-07-25 15:11
Duplicate of #207

**Closed as completed** 2016-07-25 15:11 UTC
